import raw from "./projects-data.json";
import type { FaceData } from "./face-data";

// ASCII data for each project, keyed by slugify(project.name).
// Generated by `npm run gen:projects`; empty until first run.
export const projectsData: Record<string, FaceData> = raw as Record<string, FaceData>;
